-- MySQL Script generated by MySQL Workbench
-- Qui 26 Set 2019 09:38:54 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mercado
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mercado
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mercado` DEFAULT CHARACTER SET latin1 ;
USE `mercado` ;

-- -----------------------------------------------------
-- Table `mercado`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mercado`.`clientes` (
  `id` INT(8) NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(11) NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `endereco` VARCHAR(100) NULL DEFAULT NULL,
  `telefone` VARCHAR(11) NULL DEFAULT NULL,
  `data_cadastro` DATE NOT NULL DEFAULT '2000-01-01',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpf` (`cpf` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mercado`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mercado`.`produtos` (
  `id` INT(8) NOT NULL AUTO_INCREMENT,
  `codigo_de_barras` VARCHAR(10) NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `custo` FLOAT NULL DEFAULT NULL,
  `valor_venda` FLOAT NULL DEFAULT NULL,
  `margem` VARCHAR(10) NULL DEFAULT NULL,
  `desconto` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `codigo_de_barras` (`codigo_de_barras` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mercado`.`vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mercado`.`vendas` (
  `id` INT(8) NOT NULL AUTO_INCREMENT,
  `id_cliente` VARCHAR(11) NOT NULL,
  `data_venda` DATE NOT NULL DEFAULT '2000-01-01',
  PRIMARY KEY (`id`),
  INDEX `fk_cliente` (`id_cliente` ASC),
  CONSTRAINT `fk_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `mercado`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mercado`.`corpo_venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mercado`.`corpo_venda` (
  `id` INT(8) NOT NULL AUTO_INCREMENT,
  `id_venda` INT(8) NOT NULL,
  `id_produto` VARCHAR(10) NOT NULL,
  `quantidade` INT(5) NOT NULL,
  `valor` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `id_venda`),
  INDEX `fk_venda` (`id_venda` ASC),
  INDEX `fk_produto` (`id_produto` ASC),
  CONSTRAINT `fk_produto`
    FOREIGN KEY (`id_produto`)
    REFERENCES `mercado`.`produtos` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_venda`
    FOREIGN KEY (`id_venda`)
    REFERENCES `mercado`.`vendas` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

USE `mercado`;

DELIMITER $$
USE `mercado`$$
/*!50003 CREATE */ /*!50017 DEFINER = 'root'@'localhost' */ /*!50003 TRIGGER `DEF_DATE` BEFORE INSERT ON `clientes` FOR EACH ROW BEGIN
    IF (NEW.data_cadastro = '2000-01-01') THEN
	SET NEW.data_cadastro = CURRENT_DATE;

    END IF;
    END */$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
